### ISSUE TITLE
Permission denied - /.bundle (Errno::EACCES) when executing rails-composer using the conventional approach

### ISSUE THREAD

**Issue by trein** [RailsApps/rails-composer#138]
Hi.

I tried to create a new application using rails-composer, but I keep receiving a permission denied error.

    $ rails new myapp -m https://raw.github.com/RailsApps/rails-composer/master/composer.rb

However, if I follow the second method by creating an empty application root directory (commands below), it does not happen.

    $ mkdir myapp
    $ cd myapp
    $ rvm use ruby-2.0.0@myapp --ruby-version --create
    $ gem install rails
    $ rails new . -m https://raw.github.com/RailsApps/rails-composer/master/composer.rb

Reference: http://railsapps.github.io/installrubyonrails-mac.html

The error is the following:

    composer  Installing gems. This will take a while.
        run    bundle install --without production from "."
    /Users/trein/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/vendor/thor/shell/basic.rb:336: warning: Insecure world writable dir
    /Users/trein/.rvm/gems/ruby-2.0.0-p247/bin in PATH, mode 040777
    Unfortunately, a fatal error has occurred. Please see the Bundler troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
    /Users/trein/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir': Permission denied - /.bundle (Errno::EACCES)
	from /Users/trein/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
	from /Users/trein/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
	from /Users/trein/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
	from /Users/trein/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
	from /Users/trein/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/fileutils.rb:203:in `each'
	from /Users/trein/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
	from /Users/trein/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/settings.rb:127:in `set_key'
	from /Users/trein/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/settings.rb:17:in `[]='
	from /Users/trein/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/settings.rb:79:in `without='
	from /Users/trein/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/cli.rb:237:in `install'
	from /Users/trein/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/vendor/thor/task.rb:27:in `run'
	from /Users/trein/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/vendor/thor/invocation.rb:120:in `invoke_task'
	from /Users/trein/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/vendor/thor.rb:344:in `dispatch'
	from /Users/trein/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/vendor/thor/base.rb:434:in `start'
	from /Users/trein/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/bin/bundle:20:in `block in <top (required)>'
	from /Users/trein/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/friendly_errors.rb:3:in `with_friendly_errors'
	from /Users/trein/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/bin/bundle:20:in `<top (required)>'
	from /Users/trein/.rvm/gems/ruby-2.0.0-p247@global/bin/bundle:23:in `load'
	from /Users/trein/.rvm/gems/ruby-2.0.0-p247@global/bin/bundle:23:in `<main>'
	from /Users/trein/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `eval'
	from /Users/trein/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `<main>'"""

**Comment by blaggacao** [comment]
please reopen, this is not solved

to reproduce & verify, please run this Dockerfile `docker build -t openproject:4.0 .`
https://github.com/blaggacao/openproject-docker/blob/734578741e072769a83c17235c6ed9d9c22da87f/Dockerfile

**Comment by SpaceG** [comment]
whats that mean.? Errno::EACCES: Permission denied - /Users/spaceodyssey/Desktop/hipster/vendor/bundle/ruby/2.0.0/gems/hitimes-1.2.2/.travis.yml
An error occurred while installing hitimes (1.2.2), and Bundler cannot continue.
Make sure that `gem install hitimes -v '1.2.2'` succeeds before bundling. ?

**Comment by itsNikolay** [comment]
@SpaceG 
you could try this
```
chown your_username /Users/spaceodyssey/Desktop/hipster -R
```

**Comment by eoglethorpe** [comment]
Woah that worked for me, thanks @itsNikolay 

FYI the error message I was getting was from of a Snow Plow installation on an EC2 instance with Amazon Linux
(https://github.com/snowplow/snowplow/wiki/1-Installing-EmrEtlRunner)

The message was:
```
Unfortunately, a fatal error has occurred. Please see the Bundler troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
/home/ec2-user/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir': Permission denied - /bin/snowplow/3-enrich/emr-etl-runner/.bundle (Errno::EACCES)
```

The command I ran to fix was : 
```
sudo chown ec2-user /bin/snowplow/3-enrich/emr-etl-runner -R
```

**Comment by blaggacao** [comment]
Hmm... I thought this is about fixing, and not for providing support... my2cents

**Comment by DanielKehoe** [comment]
I'm leaving this issue open because it seems some developers are encountering this issue. As far as I can tell, it is a local configuration issue and there's nothing to fix in Rails Composer. As long as people are encountering the issue, it's helpful that people are offering ideas for resolution, and hopefully it will mean everyone will have success using Rails Composer.

**Comment by kevdowney** [comment]
I'm unsure of the real cause of this issue but running as `sudo` works as the offending libraries are installed with root.

**Comment by AndyFrontera** [comment]
I faced the same problem. I'n my case i needed to run my comman from directory i've permited do "mkdir" command.

**Comment by linyixiao** [comment]
``uiui
