### ISSUE TITLE
Crashes when installing gems, `apply': uninitialized constant Rails::Generators::AppGenerator::RVM (NameError)

### ISSUE THREAD

**Issue by lukeburford** [RailsApps/rails-composer#206]
I'm on ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin13.0], rvm 1.25.15 (stable)

Starting the rails-devise tutorial using the specified options, selecting yes for project-specific rum gems creates this error:

option  Use or create a project-specific rvm gemset? (y/n) y
      extras  recipe creating project-specific rvm gemset and .rvmrc
      extras  creating RVM gemset 'rails-devise'
https://raw.github.com/RailsApps/rails-composer/master/composer.rb:2227:in `apply': uninitialized constant Rails::Generators::AppGenerator::RVM (NameError)
    from /Users/luke/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/actions.rb:223:in`instance_eval'
    from /Users/luke/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/actions.rb:223:in `apply'
    from /Users/luke/.rvm/gems/ruby-2.1.0/gems/railties-4.2.0.beta4/lib/rails/generators/app_base.rb:143:in`apply_rails_template'
    from (eval):1:in `apply_rails_template'
    from /Users/luke/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
    from /Users/luke/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/luke/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`block in invoke_all'
    from /Users/luke/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
    from /Users/luke/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`map'
    from /Users/luke/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
    from /Users/luke/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/group.rb:232:in`dispatch'
    from /Users/luke/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/luke/.rvm/gems/ruby-2.1.0/gems/railties-4.2.0.beta4/lib/rails/commands/application.rb:17:in`<top (required)>'
    from /Users/luke/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /Users/luke/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in`require'
    from /Users/luke/.rvm/gems/ruby-2.1.0/gems/railties-4.2.0.beta4/lib/rails/cli.rb:14:in `<top (required)>'
    from /Users/luke/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in`require'
    from /Users/luke/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /Users/luke/.rvm/gems/ruby-2.1.0/gems/rails-3.1.3/bin/rails:7:in`<top (required)>'
    from /Users/luke/.rvm/gems/ruby-2.1.0/bin/rails:23:in `load'
    from /Users/luke/.rvm/gems/ruby-2.1.0/bin/rails:23:in`<main>'

Any ideas?

**Comment by LuizCarvalho** [comment]
Found solution #114 , sorry!
