### ISSUE TITLE
Problem generating the rspec tutorial example

### ISSUE THREAD

**Issue by CodeItYourself** [RailsApps/rails-composer#232]
I'm trying to follow the rspec tutorial (https://tutorials.railsapps.org/tutorials/rspec-quickstart) but when I try to generate the example, it gives me an error:

https://raw.github.com/RailsApps/rails-composer/master/composer.rb:2526:in `apply': uninitialized constant Rails::Generators::AppGenerator::RVM (NameError)

I've followed along with the recomendations in the tutorial for what to select in the menu.

Here's the console error output:

```
https://raw.github.com/RailsApps/rails-composer/master/composer.rb:2526:in `apply': uninitialized constant Rails::Generators::AppGenerator::RVM (NameError)
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:223:in `instance_eval'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:223:in `apply'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/generators/app_base.rb:143:in `apply_rails_template'
	from (eval):1:in `apply_rails_template'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/application.rb:17:in `<top (required)>'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/cli.rb:14:in `<top (required)>'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/bin/rails:9:in `<top (required)>'
	from /home/alex/.rbenv/versions/2.2.2/bin/rails:23:in `load'
	from /home/alex/.rbenv/versions/2.2.2/bin/rails:23:in `<main>'
```

RVM seems to be installed and working ok, from what I can tell:

```
alex@alex-VirtualBox:~/tutorials/rspec$ rails -v
Rails 4.2.1
alex@alex-VirtualBox:~/tutorials/rspec$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
alex@alex-VirtualBox:~/tutorials/rspec$ rvm -v
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
alex@alex-VirtualBox:~/tutorials/rspec$ rvm list

rvm rubies

   ruby-2.2.1 [ x86_64 ]
 * ruby-2.2.2 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
```

Any ideas what's going on?

**Comment by CodeItYourself** [comment]
Actually, never mind. It was some problem with the setup of RVM - it didn't seem to install properly or something. I fixed it with RVM reset and then following your 'installing on ubuntu' tutorial. Seems to work now.
