### ISSUE TITLE
hard crash when rvm gem not available and attempting to create rvm gemset and .rvmrc

### ISSUE THREAD

**Issue by JohnB** [RailsApps/rails-composer#26]
Just got this crash. I'll fork the repo and try to work around it (not raise an exception - just log the issue and move on). Note that I have the rvm application installed but the gem is not currently available.

      ...
      extras  Create a project-specific rvm gemset and .rvmrc? (y/n) y
      extras  Create a GitHub repository? (y/n) y
      extras  recipe banning spiders by modifying 'public/robots.txt'
      extras  recipe creating project-specific rvm gemset and .rvmrc
https://raw.github.com/RailsApps/rails-composer/master/composer.rb:1663:in `rescue in apply': RVM gem is currently unavailable. (RuntimeError)
	from https://raw.github.com/RailsApps/rails-composer/master/composer.rb:1657:in `apply'
	from /Users/jbaylor/.rvm/gems/ruby-1.9.2-p290@jbaylor_personal/gems/thor-0.14.6/lib/thor/actions.rb:217:in `instance_eval'
	from /Users/jbaylor/.rvm/gems/ruby-1.9.2-p290@jbaylor_personal/gems/thor-0.14.6/lib/thor/actions.rb:217:in `apply'
	from /Users/jbaylor/.rvm/gems/ruby-1.9.2-p290@jbaylor_personal/gems/railties-3.2.8/lib/rails/generators/app_base.rb:109:in `apply_rails_template'
	from (eval):1:in `apply_rails_template'
	from /Users/jbaylor/.rvm/gems/ruby-1.9.2-p290@jbaylor_personal/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
	from /Users/jbaylor/.rvm/gems/ruby-1.9.2-p290@jbaylor_personal/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
	from /Users/jbaylor/.rvm/gems/ruby-1.9.2-p290@jbaylor_personal/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `block in invoke_all'
	from /Users/jbaylor/.rvm/gems/ruby-1.9.2-p290@jbaylor_personal/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `each'
	from /Users/jbaylor/.rvm/gems/ruby-1.9.2-p290@jbaylor_personal/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `map'
	from /Users/jbaylor/.rvm/gems/ruby-1.9.2-p290@jbaylor_personal/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `invoke_all'
	from /Users/jbaylor/.rvm/gems/ruby-1.9.2-p290@jbaylor_personal/gems/thor-0.14.6/lib/thor/group.rb:226:in `dispatch'
	from /Users/jbaylor/.rvm/gems/ruby-1.9.2-p290@jbaylor_personal/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
	from /Users/jbaylor/.rvm/gems/ruby-1.9.2-p290@jbaylor_personal/gems/railties-3.2.8/lib/rails/commands/application.rb:38:in `<top (required)>'
	from /Users/jbaylor/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:54:in `require'
	from /Users/jbaylor/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:54:in `require'
	from /Users/jbaylor/.rvm/gems/ruby-1.9.2-p290@jbaylor_personal/gems/railties-3.2.8/lib/rails/cli.rb:15:in `<top (required)>'
	from /Users/jbaylor/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:54:in `require'
	from /Users/jbaylor/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:54:in `require'
	from /Users/jbaylor/.rvm/gems/ruby-1.9.2-p290@jbaylor_personal/gems/railties-3.2.8/bin/rails:7:in `<top (required)>'
	from /Users/jbaylor/.rvm/gems/ruby-1.9.2-p290@jbaylor_personal/bin/rails:19:in `load'
	from /Users/jbaylor/.rvm/gems/ruby-1.9.2-p290@jbaylor_personal/bin/rails:19:in `<main>'

**Comment by DanielKehoe** [comment]
Getting this error when running Rails Composer with Ruby 2.2.3 and Rails 4.2.5.

See https://github.com/rvm/rvm-gem/issues/16
