### ISSUE TITLE
[Feature request] Support for Rails 6.0.0

### ISSUE THREAD

**Issue by jarl-dk** [RailsApps/rails-composer#283]
Trying to use composer with Rails 6.0.0 complains with the misleading error message:
```
https://raw.github.com/RailsApps/rails-composer/master/composer.rb:279:in `apply': Rails 6.0.0 is not supported. Use Rails 4.1 or newer. (StandardError)
```

**Comment by emacielxp** [comment]
same problem here with rails 6.0.2.2:

`You are using Rails version 6.0.2.2 which is not supported. Use Rails 4.1 or newer.`

**Comment by louie728** [comment]
Same here... :(
Rails version 6.0.3
`https://raw.github.com/RailsApps/rails-composer/master/composer.rb:279:in `apply': Rails 6.0.3 is not supported. Use Rails 4.1 or newer. (StandardError)`

**Comment by joaotorres** [comment]
Any alternatives until it's supported? :|

**Comment by TrindadeF** [comment]
the same problem here
Rails version 7.0.3 
`https://raw.github.com/RailsApps/rails-composer/master/composer.rb:279:in `apply': Rails 7.0.3 is not supported. Use Rails 4.1 or newer. (StandardError)`
